### ISSUE TITLE
It can't be built at all.

### ISSUE THREAD

**Issue by Gerrie-Cui** [OrangeX4/GitNotes#2]
After reading the README, I don't know what to do.

**Comment by OrangeX4** [comment]
I am sorry that my description is not clear.

You are supposed to download [NodeJS](https://nodejs.org/en/), install it in your computer.

Then run the command `npm install yarn -g`, and run `npm install` in terminal in the folder you have cloned.

Finally, you can run the command `yarn start` for dev server or `yarn build` for static files.
