### ISSUE TITLE
引用显示问题

### ISSUE THREAD

**Issue by Ghjk94522** [OrangeX4/GitNotes#3]
`markdown` 中的引用部分显示不正确，可能是跟不同的 `markdown`  语法解释不同有关？

比如我输入：

``` markdown
> 导数介值定理：若函数的导数在区间端点值不相等，则区间内存在一点可以取到两端点导数值之间任何值（可以不考虑导数连续性）
```

在网页中会按照无语法显示，即无法和正常文本区分开

**Comment by OrangeX4** [comment]
可能是还未添加对应正确的 CSS 导致的, 我之后会修复这个 bug.

**Comment by OrangeX4** [comment]
已更新 CSS，该问题已解决，可以重新浏览或重新部署，即可看到效果。

**Comment by Ghjk94522** [comment]
貌似新功能引起了一些新 bug ，引用内的公式会导致解析错误？（根据目前的页面猜测的

提供一个地址：[传送门](https://notes.orangex4.cool/?git=gitlab&gitlab=git.nju.edu.cn&id=3349)

里面的 `gcuu/6_中值定理.md` 里面就可以看到新内容显示

[markdown 原内容](https://gitee.com/nutshe11/math_note/raw/master/gcuu/6_%E4%B8%AD%E5%80%BC%E5%AE%9A%E7%90%86.md)

建议回滚一下版本hh (x

**Comment by OrangeX4** [comment]
抱歉, 我这就去看看 :-(

**Comment by OrangeX4** [comment]
总算修好了，现在应该没问题了。

感谢你提的 issue！

**Comment by OrangeX4** [comment]
部署其实不难，可以照着说明随便改改就好，实在不清楚也欢迎联系我 :-)

**Comment by Ghjk94522** [comment]
hh，感谢大佬学弟提供这么好用的 note 平台了:P
