### ISSUE TITLE
请问图片应该用什么格式才能显示出来

### ISSUE THREAD

**Issue by yangduojin** [OrangeX4/GitNotes#5]
我将图片保存到img文件夹内,在md中引用,  github的浏览页面是可以看到图片的,但是在你这个应用里面就不能看见图片,不知道为什么,
是必须要网络图片才可以访问到吗

**Comment by OrangeX4** [comment]
网络图片肯定能访问到, 如果保存到了 img 文件夹内, 你试试 `![](./img/xxx.jpg)` 这种语法? 注意前面的 `./`
