### ISSUE TITLE
这个未来有支持 Gitea 的计划吗~

### ISSUE THREAD

**Issue by LiaoSirui** [OrangeX4/GitNotes#6]

**Comment by OrangeX4** [comment]
之后有时间的话会支持的.

**Comment by OrangeX4** [comment]
等有时间可能会支持。



---Original---
From: ***@***.***&gt;
Sent at: 2022年7月30日(Sat) AM10:01
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [OrangeX4/GitNotes] 这个未来有支持 Gitea 的计划吗~ (Issue #6)
